/* Night Elite Ludo frontend. Demo adapter (localStorage) sits behind `API`; swap its methods for fetch('/api/...') calls. */
const CFG={DEMO_WALLET:true,ENABLE_REAL_MONEY:false,ENABLE_CASHFREE:false,ENABLE_KYC:false,FEE:.025,NOTICE:'Demo mode: sandbox coins only. No real money is used.',WA:'https://wa.me/918302402126',OTP_COOLDOWN:30,OTP_MAX:5,MIN_STAKE:50};
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>'₹'+Number(n).toFixed(2),KEY='fb_demo_v1';
const BOTS=['Kartik tiwari','Gujjar ji','TurboWin','PowerDice','LuckyChamp','Kingkhan','NightHawk'];
let S=JSON.parse(localStorage.getItem(KEY)||'null')||{user:null,battles:[],ledger:[],notes:[],otp:null};
const FBC=window.FB_CONFIG||{},REAL=!!(FBC.SUPABASE_URL&&FBC.SUPABASE_ANON_KEY&&window.supabase);let UID=null;if(REAL)S={user:null,battles:[],ledger:[],notes:[],otp:null};
const save=()=>{REAL||localStorage.setItem(KEY,JSON.stringify(S))};
const toast=m=>{const t=$('#toast');t.textContent=m;t.className='on';clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='',2200)};
const prize=s=>+(s*2*(1-CFG.FEE*2)).toFixed(2);
const seed=()=>{if(S.battles.filter(b=>b.st==='open'&&b.bot).length<4){for(let i=0;i<5;i++){const s=[100,200,450,1100,2000][i];S.battles.push({id:crypto.randomUUID(),st:'open',by:BOTS[i],bot:1,stake:s,at:Date.now()-i*1e5})}if(!S.battles.some(b=>b.st==='running'&&b.bot))[['Kingkhan','Ps meeNa',200],['EliteRoll','NightHawk',1000],['PowerDice','LuckyChamp',2850]].forEach(([a,c,x])=>S.battles.push({id:crypto.randomUUID(),st:'running',by:a,opp:c,bot:1,stake:x,at:Date.now()}));save()}};
const led=(t,a,note)=>{S.ledger.unshift({id:crypto.randomUUID(),t,a,note,at:Date.now()});S.ledger=S.ledger.slice(0,200)};
/* ---- API adapter (demo) ---- */
const API={
 async sendOtp(p){if(!/^[6-9]\d{9}$/.test(p))throw Error('Enter a valid 10-digit mobile number.');
  if(S.otp&&Date.now()-S.otp.at<CFG.OTP_COOLDOWN*1e3)throw Error('Wait before requesting another OTP.');
  S.otp={p,at:Date.now(),tries:0};save()},
 async verifyOtp(c){const o=S.otp;if(!o)throw Error('Request an OTP first.');if(Date.now()-o.at>3e5)throw Error('OTP expired. Request a new one.');
  if(++o.tries>CFG.OTP_MAX){S.otp=null;save();throw Error('Too many attempts. Request a new OTP.')}
  if(!/^\d{6}$/.test(c))throw Error('Enter the 6-digit OTP.');save();
  if(!S.user)S.user={phone:o.p,name:'FastUser'+Math.floor(1000+Math.random()*9000),funds:0,income:0,won:0,games:0,kyc:false,ref:Math.random().toString(36).slice(2,8).toUpperCase(),refs:0};
  S.otp=null;seed();save()},
 async addCash(a){if(!CFG.DEMO_WALLET)throw Error('Payments are not enabled.');if(!(a>=10&&a<=10000))throw Error('Enter ₹10 to ₹10,000.');S.user.funds+=a;led('Demo deposit',a,'Sandbox money');save()},
 async create(s){if(!(s>=CFG.MIN_STAKE))throw Error('Minimum entry is '+CFG.MIN_STAKE+' coins.');if(s>S.user.funds)throw Error('Not enough deposit coins. Add cash first.');
  S.user.funds-=s;led('Battle stake locked',-s,'Created battle');S.battles.unshift({id:crypto.randomUUID(),st:'open',by:S.user.name,mine:1,stake:s,at:Date.now()});save()},
 async cancel(id){const b=S.battles.find(x=>x.id===id&&x.mine&&x.st==='open');if(!b)return;b.st='cancelled';S.user.funds+=b.stake;led('Stake refunded',b.stake,'Battle cancelled');save()},
 async join(id){const b=S.battles.find(x=>x.id===id&&x.st==='open'&&!x.mine);if(!b)throw Error('Battle is no longer open.');if(b.stake>S.user.funds)throw Error('Not enough deposit coins. Add cash first.');
  S.user.funds-=b.stake;led('Battle stake locked',-b.stake,'Joined '+b.by);b.st='running';b.opp=S.user.name;b.joined=1;b.end=Date.now()+8e3;save()},
 settle(){let ch=0;S.battles.forEach(b=>{if(b.mine&&b.st==='open'&&Date.now()-b.at>6e3){b.st='running';b.opp=BOTS[Math.floor(Math.random()*BOTS.length)];ch=1}});(S.wds||[]).forEach(w=>{if(w.status==='pending'&&Date.now()>w.at+1e4){w.status='paid';S.notes.unshift({m:'Withdrawal of ₹'+w.amount+' paid',at:Date.now(),r:0});ch=1}});S.battles.forEach(b=>{if(b.st==='running'&&b.end<=Date.now()&&b.joined&&b.auto){b.st='done';const w=Math.random()<.5;b.won=w;S.user.games++;
   if(w){const p=prize(b.stake);S.user.income+=p;S.user.won+=p;led('Battle won',p,'vs '+b.by);S.notes.unshift({m:'You won '+fmt(p)+' against '+b.by,at:Date.now(),r:0})}
   else S.notes.unshift({m:'You lost '+b.stake+' coins against '+b.by,at:Date.now(),r:0});ch=1}});if(ch)save();return ch},
 async ticket(sj,b){if(sj.length<3||b.length<5)throw Error('Add a subject and a message.');S.tickets=S.tickets||[];if(S.tickets.filter(t=>t.status==='open').length>=5)throw Error('Too many open tickets.');S.tickets.unshift({id:crypto.randomUUID(),subject:sj,status:'open',reply:null,created_at:new Date().toISOString()});save()},
 demoFinish(id,won){const b=S.battles.find(x=>x.id===id);if(!b||b.st!=='running')return;b.st='done';b.won=won;S.user.games++;const vs=b.mine?b.opp:b.by;if(won){const p=prize(b.stake);S.user.income+=p;S.user.won+=p;led('Battle won',p,'vs '+vs);S.notes.unshift({m:'You won '+(+p.toFixed(2))+' coins against '+vs,at:Date.now(),r:0})}else S.notes.unshift({m:'You lost '+b.stake+' coins against '+vs,at:Date.now(),r:0});if(S.games)delete S.games[id];save()},
 async kyc(n,e,m,b,a,ad){if(S.user.kyc||S.user.kycs==='pending')throw Error('KYC already submitted.');if(n.trim().length<3)throw Error('Enter your full name.');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e))throw Error('Enter a valid email address.');if(!/^[6-9]\d{9}$/.test(m))throw Error('Enter a valid 10-digit mobile number.');if(!aadhaarOk(a))throw Error('Invalid Aadhaar number.');if((ad||'').trim().length<10)throw Error('Enter your full address.');if(!KB.f||!KB.b)throw Error('Add the front and back photos of your Aadhaar.');if(!b||new Date(b)>new Date(Date.now()-18*31557600000))throw Error('You must be 18 or older.');S.kycForm={name:n.trim(),email:e,mobile:m,dob:b,last4:a.slice(-4),address:ad.trim()};S.user.kycs='pending';save()},
 async withdraw(a,m,d){if(!S.user.kyc)throw Error('Complete KYC to withdraw.');if(!(a>=100))throw Error('Minimum withdrawal is ₹100.');if(a>S.user.income)throw Error('Not enough winning coins.');if(m==='upi'?!/^[\w.\-]{2,}@[A-Za-z]{2,}$/.test(d):d.trim().length<5)throw Error('Enter valid payout details.');S.user.income-=a;led('Withdrawal requested',-a,'Demo withdrawal');S.wds=S.wds||[];S.wds.unshift({id:crypto.randomUUID(),amount:a,status:'pending',method:m,at:Date.now()});save()}
};
/* ---- Real backend adapter (Supabase + /api). Active only when js/config.js has URL + anon key. ---- */
const EM={TOO_MANY:'Too many attempts. Wait a few minutes and try again.',QR_UNAVAILABLE:'Could not generate the QR right now. Try again.',PAYMENTS_DISABLED:'Payments are not available right now.',NOT_FOUND:'Payment not found.',BAD_ADDRESS:'Enter your full address.',DOCS_MISSING:'Add the front and back photos of your Aadhaar.',BAD_AADHAAR:'Invalid Aadhaar number.',AADHAAR_USED:'This Aadhaar is already linked to another account.',BAD_EMAIL:'Enter a valid email address.',BAD_MOBILE:'Enter a valid 10-digit mobile number.',KYC_UNAVAILABLE:'KYC is temporarily unavailable.',KYC_EXISTS:'KYC already submitted.',BAD_KYC:'Enter your full name and the last 4 characters of your ID.',UNDERAGE:'You must be 18 or older.',MIN_WITHDRAW:'Amount is below the minimum withdrawal.',BAD_DETAIL:'Enter valid payout details.',PAYMENTS_DISABLED:'Online payments are not enabled.',PAYMENT_FAILED:'Could not start the payment. Try again.',BAD_TICKET:'Add a subject (3+ characters) and a message (5+).',TOO_MANY_TICKETS:'You have 5 open tickets. Wait for a reply first.',BAD_CODE:'Room code: 4–12 letters or numbers.',ALREADY_REPORTED:'You already reported this result.',BAD_CLAIM:'Invalid result.',INSUFFICIENT_FUNDS:'Not enough coins. Add cash first.',BAD_STAKE:'Enter a whole number, minimum 50 coins.',NOT_OPEN:'Battle is no longer open.',OWN_BATTLE:'You cannot join your own battle.',NOT_ALLOWED:'Not allowed.',DEMO_DISABLED:'Adding cash is disabled.',BAD_AMOUNT:'Enter ₹10 to ₹10,000.',WITHDRAW_DISABLED:'Withdrawals are disabled in demo mode.',KYC_REQUIRED:'Complete KYC to withdraw.',AUTH:'Please log in again.',BAD_PHONE:'Enter a valid 10-digit mobile number.',COOLDOWN:'Wait 30 seconds before requesting another OTP.',RATE_LIMIT:'Too many OTP requests. Try again later.',OTP_UNAVAILABLE:'OTP service is unavailable. Try later.',SMS_BALANCE:'SMS service is out of balance. Contact support.',SMS_FAILED:'Could not send OTP. Try again.',OTP_EXPIRED:'OTP expired. Request a new one.',WRONG_OTP:'Wrong OTP.',TOO_MANY_ATTEMPTS:'Too many attempts. Request a new OTP.'};
const em=m=>{const k=Object.keys(EM).find(k=>String(m).includes(k));return k?EM[k]:'Something went wrong. Try again.'};
let sb=null;
if(REAL){sb=window.supabase.createClient(FBC.SUPABASE_URL,FBC.SUPABASE_ANON_KEY);
 const http=async(p,b)=>{let r,j;try{r=await fetch('/api'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});j=await r.json()}catch{throw Error('Network error. Check your connection.')}if(!r.ok)throw Error(em(j.error));return j};
 const rpc=async(n,a)=>{const{error}=await sb.rpc(n,a);if(error)throw Error(em(error.message));await API.refresh()};
 Object.assign(API,{
  async sendOtp(p){if(!/^[6-9]\d{9}$/.test(p))throw Error(EM.BAD_PHONE);await http('/auth/send-otp',{phone:p});S.otp={p,at:Date.now(),tries:0}},
  async verifyOtp(c){if(!S.otp)throw Error('Request an OTP first.');if(!/^\d{6}$/.test(c))throw Error('Enter the 6-digit OTP.');
   const j=await http('/auth/verify-otp',{phone:S.otp.p,code:c});await sb.auth.setSession({access_token:j.session.access_token,refresh_token:j.session.refresh_token});S.otp=null;
   const ref=new URLSearchParams(location.search).get('ref');if(ref)await sb.rpc('apply_referral',{p_code:ref});await API.refresh()},
  create:s=>rpc('create_battle',{p_stake:s}),join:id=>rpc('join_battle',{p_id:id}),cancel:id=>rpc('cancel_battle',{p_id:id}),
  addCash:a=>rpc('demo_add_cash',{p_amount:a}),withdraw:(a,m,d)=>rpc('request_withdrawal',{p_amount:a,p_method:m,p_detail:d}),async kyc(n,e,m,b,a,ad){if(!KB.f||!KB.b)throw Error('Add the front and back photos of your Aadhaar.');for(const[k,nm]of[['f','front'],['b','back']]){const{error}=await sb.storage.from('kyc').upload(`${UID}/${nm}.jpg`,KB[k],{upsert:true,contentType:'image/jpeg'});if(error)throw Error('Could not upload your photos. Try again.')}const{data:{session}}=await sb.auth.getSession();const x=await fetch('/api/kyc/submit',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({name:n,email:e,mobile:m,dob:b,aadhaar:a,address:ad})}).then(r=>r.json()).catch(()=>({error:'NETWORK'}));if(x.error)throw Error(em(x.error));await API.refresh()},
  async apiF(path,o={}){const{data:{session}}=await sb.auth.getSession();return fetch(path,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(session?session.access_token:'')}}).then(r=>r.json()).catch(()=>({error:'NETWORK'}))},
  async createQr(a){const x=await API.apiF('/api/payments/create-order',{method:'POST',body:JSON.stringify({amount:a})});if(!x.order_id)throw Error(em(x.error));return x},
  settle:()=>0,ticket:(s,b)=>rpc('create_ticket',{p_subject:s,p_body:b}),setRoom:(id,c)=>rpc('set_room_code',{p_id:id,p_code:c}),report:(id,c)=>rpc('report_result',{p_id:id,p_claim:c}),
  async markRead(){await sb.from('notifications').update({read:true}).eq('user_id',UID).eq('read',false)},
  async refresh(){const{data:{session}}=await sb.auth.getSession();
   if(!session){const had=!!S.user;S.user=null;return had}
   const uid=UID=session.user.id,q=(t,c)=>sb.from(t).select(c);
   const[p,w,f,l,n,st,mb,tk,wd,an]=await Promise.all([q('profiles','phone,name,ref_code,kyc_status,kyc_note').eq('id',uid).single(),q('wallets','deposit,winning').eq('user_id',uid).single(),
    q('battle_feed','id,stake,prize,status,creator,creator_name,opponent_name').order('created_at',{ascending:false}).limit(30),
    q('wallet_ledger','amount,kind,note,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(100),
    q('notifications','message,read,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(30),sb.rpc('my_stats'),sb.rpc('my_battles'),q('support_tickets','id,subject,status,reply,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(20),q('withdrawals','id,amount,status,payout_method,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(10),
    sb.from('announcements').select('message').eq('active',true).or('expires_at.is.null,expires_at.gt.'+new Date().toISOString()).order('created_at',{ascending:false}).limit(1).then(r=>r,()=>({data:null}))]);
   if(p.error||w.error)return false;const old=JSON.stringify(S),s=st.data||{};
   S.user={phone:p.data.phone,name:p.data.name,ref:p.data.ref_code,kyc:p.data.kyc_status==='verified',kycs:p.data.kyc_status,kycNote:p.data.kyc_note,funds:+w.data.deposit,income:+w.data.winning,won:+(s.won||0),games:+(s.games||0),refs:+(s.refs||0),refEarn:+(s.refearn||0)};S.ann=(!an.error&&an.data&&an.data[0]&&String(an.data[0].message||'').trim())||'';S.mine=mb.data||[];S.tickets=tk.data||[];S.wds=(wd.data||[]).map(x=>({id:x.id,amount:+x.amount,status:x.status,method:x.payout_method,at:new Date(x.created_at).getTime()}));
   S.battles=(f.data||[]).map(b=>({id:b.id,st:b.status,by:b.creator_name,opp:b.opponent_name,stake:+b.stake,prize:+b.prize,mine:b.creator===uid}));
   S.ledger=(l.data||[]).map(x=>({t:x.note||x.kind,a:+x.amount,at:new Date(x.created_at).getTime()}));
   S.notes=(n.data||[]).map(x=>({m:x.message,r:x.read,at:new Date(x.created_at).getTime()}));
   return JSON.stringify(S)!==old},
  async boot(){await API.refresh();sb.auth.onAuthStateChange(ev=>{if(ev==='SIGNED_OUT'&&S.user){S.user=null;render()}})}
 })}
/* ---- UI ---- */
const P={home:'M3 11l9-8 9 8M5 10v10h14V10M10 20v-6h4v6',wallet:'M3 7a2 2 0 012-2h13v4M3 7v11a2 2 0 002 2h15V9H5a2 2 0 01-2-2M16 14.5h.01',gift:'M20 12v9H4v-9M2 7h20v5H2zM12 21V7M12 7S11 3 8.5 3a2 2 0 000 4M12 7s1-4 3.5-4a2 2 0 010 4',chat:'M21 12a8 8 0 01-11.5 7.2L4 20l1-4.5A8 8 0 1121 12z',user:'M20 21a8 8 0 10-16 0M12 12a4 4 0 100-8 4 4 0 000 8z',menu:'M4 7h16M4 12h16M4 17h16',bell:'M6 9a6 6 0 1112 0c0 6 2 7 2 7H4s2-1 2-7M10 20a2 2 0 004 0',clock:'M12 7v5l3 2M21 12a9 9 0 11-18 0 9 9 0 0118 0z',out:'M15 17l5-5-5-5M20 12H9M9 4H5v16h4',wa:'M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z',x:'M6 6l12 12M18 6L6 18',plus:'M12 5v14M5 12h14',bank:'M3 10l9-6 9 6M5 10v8M9 10v8M15 10v8M19 10v8M3 20h18',copy:'M9 9h10v11H9zM5 15V4h10',tg:'M21 4L3 11l6 2 2 7 3-4 5 4z',shield:'M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6zM12 8v5M12 16h.01',doc:'M7 3h8l4 4v14H7zM15 3v4h4M10 12h6M10 16h6',dl:'M12 4v11M7 11l5 5 5-5M5 20h14',uplus:'M15 20a6 6 0 10-12 0M9 12a4 4 0 100-8 4 4 0 000 8zM19 8v6M16 11h6',arr:'M5 12h14M13 6l6 6-6 6',info:'M12 8h.01M11 12h1v5h1M21 12a9 9 0 11-18 0 9 9 0 0118 0z',pen:'M4 20l4-1 11-11-3-3L5 16z',star:'M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z',check:'M5 12l5 5 9-10',walk:'M13 5a1 1 0 100 .01M9 21l2-6-2-2 1-5 4 2 2 3M11 15l3 2v4',scan:'M4 8V5a1 1 0 011-1h3M16 4h3a1 1 0 011 1v3M20 16v3a1 1 0 01-1 1h-3M8 20H5a1 1 0 01-1-1v-3M7 12h10',cam:'M4 8h3l2-3h6l2 3h3v11H4zM12 17a3.5 3.5 0 100-7 3.5 3.5 0 000 7z',snd:'M4 9v6h4l5 4V5L8 9zM16 9a4 4 0 010 6M18.5 6.5a8 8 0 010 11',mute:'M4 9v6h4l5 4V5L8 9zM17 9l5 6M22 9l-5 6'};
const ic=n=>`<svg viewBox="0 0 24 24"${n==='wa'?' class="f"':''} aria-hidden="true"><path d="${P[n]}"/></svg>`,nf=n=>+(+n).toFixed(2),coin='<i class="coin">₹</i>';
const logo=`<span class="bl"><img class="lg" src="assets/logo-h.png" alt="Night Elite Ludo" width="34" height="34"><span class="wm" aria-hidden="true">Night Elite<b>Ludo</b></span></span>`;
const art=k=>{const t=(y,s,x=75)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${s}" font-weight="900" fill="#ffffff" stroke="#2a1670" stroke-width="5" paint-order="stroke" font-family="Poppins,Arial Black,sans-serif">`;
 return`<svg viewBox="0 0 150 160"><defs><linearGradient id="g${k}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#8a6bff"/><stop offset="1" stop-color="#4B2BBF"/></linearGradient></defs><rect width="150" height="160" rx="16" fill="url(#g${k})"/>${k?'<path d="M10 150c14-30 30 6 42-18s26-8 22-34" stroke="#2f9e44" stroke-width="13" fill="none" stroke-linecap="round"/><circle cx="76" cy="92" r="10" fill="#2f9e44"/>':''}<g transform="translate(78 108) rotate(-8)"><rect x="-44" y="-44" width="88" height="88" rx="8" fill="#fff"/><rect x="-40" y="-40" width="36" height="36" fill="#ef4444"/><rect x="4" y="-40" width="36" height="36" fill="#22a755"/><rect x="-40" y="4" width="36" height="36" fill="#f5c518"/><rect x="4" y="4" width="36" height="36" fill="#2f6bf3"/><rect x="-9" y="-9" width="18" height="18" rx="3" fill="#fff"/></g><g transform="rotate(14 128 118)"><rect x="112" y="102" width="32" height="32" rx="7" fill="#fff" stroke="#ccc"/><circle cx="121" cy="111" r="3"/><circle cx="135" cy="125" r="3"/><circle cx="128" cy="118" r="3"/></g>${t(32,27)}LUDO</text>${t(58,k?25:22)}${k?'SNAKE':'CLASSIC'}</text>${k?'':`<rect x="42" y="64" width="66" height="15" rx="7" fill="#2a1670" opacity=".0"/>`}</svg>`};
const heroArt=()=>{const Y=[['#ff8a80','#e53935','#8e1313'],['#8be39f','#2e9d4f','#0f5a2a'],['#ffe27a','#f6b800','#a87500'],['#8fc4ff','#1e6fe0','#0b3a8f']],Q=[[0,0],[9,0],[9,9],[0,9]];
let o='<svg class="hg-svg" viewBox="0 0 300 190" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><radialGradient id="hbg" cx=".5" cy=".4" r=".8"><stop offset="0" stop-color="#5b3fd6"/><stop offset="1" stop-color="#1a0d4d"/></radialGradient><linearGradient id="hfr" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d9cfff"/><stop offset=".5" stop-color="#6D4AFF"/><stop offset="1" stop-color="#d9cfff"/></linearGradient><radialGradient id="hdi" cx=".3" cy=".25" r=".9"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#d9d3ee"/></radialGradient>'+Y.map(([a,b,c],n)=>`<linearGradient id="hy${n}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient><radialGradient id="hp${n}" cx=".32" cy=".28" r=".85"><stop offset="0" stop-color="${a}"/><stop offset=".55" stop-color="${b}"/><stop offset="1" stop-color="${c}"/></radialGradient>`).join('')+'</defs><rect width="300" height="190" fill="url(#hbg)"/><g transform="translate(150 96) rotate(-7) scale(11.6) translate(-7.5 -7.5)"><rect x="-.35" y="-.35" width="15.7" height="15.7" rx=".7" fill="url(#hfr)"/><rect width="15" height="15" fill="#fff"/>';
Q.forEach(([c,r],n)=>{o+=`<rect x="${c}" y="${r}" width="6" height="6" fill="url(#hy${n})"/><rect x="${c+1}" y="${r+1}" width="4" height="4" rx=".8" fill="#fffffff2"/>`;[[2,2],[4,2],[2,4],[4,4]].forEach(([p,q])=>o+=`<circle cx="${c+p}" cy="${r+q}" r=".62" fill="${Y[n][1]}" opacity=".28"/>`)});
const cl=(r,c,f)=>`<rect x="${c}" y="${r}" width="1" height="1" fill="${f}" stroke="#cfc6ee" stroke-width=".05"/>`;
for(let k=0;k<15;k++){for(const d of[6,7,8]){if(k<6||k>8){o+=cl(d,k,d===7&&k>0&&k<6?'url(#hy0)':d===7&&k>8&&k<14?'url(#hy2)':'#fff');o+=cl(k,d,d===7&&k>0&&k<6?'url(#hy1)':d===7&&k>8&&k<14?'url(#hy3)':'#fff')}}}
o+=cl(6,1,'url(#hy0)')+cl(1,8,'url(#hy1)')+cl(8,13,'url(#hy2)')+cl(13,6,'url(#hy3)');
o+='<polygon points="6,6 6,9 7.5,7.5" fill="url(#hy0)"/><polygon points="6,6 9,6 7.5,7.5" fill="url(#hy1)"/><polygon points="9,6 9,9 7.5,7.5" fill="url(#hy2)"/><polygon points="6,9 9,9 7.5,7.5" fill="url(#hy3)"/>';
const pawn=(x,y,n)=>`<g transform="translate(${x} ${y}) rotate(7) scale(.056)"><ellipse cy="14" rx="11" ry="3.6" fill="#0007"/><path d="M-10 14 Q-9 1 -4 -4 L4 -4 Q9 1 10 14Z" fill="url(#hp${n})" stroke="#fff" stroke-width="1.4"/><circle cy="-10" r="8" fill="url(#hp${n})" stroke="#fff" stroke-width="1.4"/><ellipse cx="-2.6" cy="-13" rx="2.6" ry="1.8" fill="#fff" opacity=".75"/></g>`;
Q.forEach(([c,r],n)=>[[2,2],[4,2],[2,4],[4,4]].forEach(([p,q])=>o+=pawn(c+p,r+q-.25,n)));o+='</g>';
o+='<g transform="translate(150 94) rotate(14)"><rect x="-22" y="-20" width="44" height="44" rx="10" fill="#0006" transform="translate(3 6)"/><rect x="-22" y="-22" width="44" height="44" rx="10" fill="url(#hdi)" stroke="#fff" stroke-width="1.5"/>'+[[-11,-11],[11,-11],[-11,0],[11,0],[-11,11],[11,11]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3.6" fill="#1b1530"/>`).join('')+'</g></svg>';return o};
const avatar=`<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="31" fill="#eaf3ff"/><path d="M12 62c2-14 12-18 20-18s18 4 20 18z" fill="#4f8df5"/><circle cx="32" cy="30" r="11" fill="#ffd0a6"/><path d="M20 28c0-12 24-12 24 0-6-3-18-3-24 0z" fill="#1f3a8a"/><circle cx="28" cy="31" r="1.3" fill="#222"/><circle cx="36" cy="31" r="1.3" fill="#222"/><path d="M28 36q4 3 8 0" stroke="#b5532a" fill="none" stroke-linecap="round"/><path d="M8 14l1.5 3 3 1.5-3 1.5L8 23l-1.5-3L3.500 18.500 6.500 17zM54 8l1 2 2 1-2 1-1 2-1-2-2-1 2-1z" fill="#b9a6ff"/></svg>`;
const wa=`<a class="fab" href="${CFG.WA}" target="_blank" rel="noopener" aria-label="WhatsApp support">${ic('wa')}</a>`;
const TABS=[['home','Home','home'],['refer','Refer','gift'],['wallet','Wallet','wallet'],['support','Support','chat'],['profile','Profile','user']];
const head=()=>{const u=S.user,n=S.notes.filter(x=>!x.r).length;return`<header><div class="h1"><button class="menu" data-a="menu" aria-label="Menu">${ic('menu')}</button>${logo}<span class="sp"></span><a class="bell" href="#/notifications" aria-label="Notifications">${ic('bell')}${n?`<b>${n}</b>`:''}</a></div><div class="h2"><a class="chip" href="#/wallet"><i class="g">${ic('wallet')}</i><span><small>FUNDS</small>${fmt(u.funds)}</span></a><a class="chip" href="#/wallet"><i class="o">${ic('gift')}</i><span><small>INCOME</small>${fmt(u.income)}</span></a></div></header>`};
const nav=r=>`<nav>${TABS.map(([k,l,i])=>`<a href="#/${k}" class="${r===k?'on':''}"><b>${ic(i)}</b>${l}</a>`).join('')}</nav>`;
const drawer=`<div id="drawer" data-a="dclose"><div><h3><img class="dm" src="assets/mark.png" alt=""><span>Night Elite Ludo</span><button data-a="dclose" aria-label="Close">${ic('x')}</button></h3>${[['home','Home','home'],['profile','My Profile','user'],['wallet','My Wallet','wallet'],['refer','Refer & Earn','uplus'],['history','History','doc'],['notifications','Notifications','bell'],['support','Support','doc']].map(([k,l,i])=>`<a href="#/${k}" data-a="dclose"><span>${ic(i)}</span>${l}</a>`).join('')}<a href="#" data-a="install"><span>${ic('dl')}</span>Install App</a></div></div>`;
const bCard=b=>b.st==='open'?`<div class="bc"><h4>Challenge From <b>${esc(b.by)}</b></h4><div class="in"><span><small>Entry Fee</small><strong>${coin}${nf(b.stake)}</strong></span>${b.mine?`<button class="play" data-a="cancel" data-id="${b.id}">Cancel</button>`:`<button class="play" data-a="join" data-id="${b.id}">Play</button>`}<span class="r"><small>Winning Prize</small><strong>${coin}${nf(b.prize??prize(b.stake))}</strong></span></div></div>`
:`<div class="bc run"><h4><b>${esc(b.by)}</b> vs <b>${esc(b.opp||'Player')}</b></h4><div class="in"><span><small>Entry Fee</small><strong>${coin}${nf(b.stake)}</strong></span><span class="vs">VS</span><span class="r"><small>Winning Prize</small><strong>${coin}${nf(b.prize??prize(b.stake))}</strong></span></div></div>`;
const li=(k,i,l,x='')=>`<a class="li ${x}" href="#/${k}"><span>${ic(i)}</span>${l}<em>${ic('arr').replace('M5 12h14M13 6l6 6-6 6','M9 6l6 6-6 6')}</em></a>`;
const MINE=()=>REAL?(S.mine||[]):S.battles.filter(b=>b.st==='running'&&(b.joined||b.mine)).map(b=>({id:b.id,stake:b.stake,prize:prize(b.stake),status:'running',vs:b.mine?b.opp:b.by}));
const mm=()=>MINE().length?`<div class="bar">${ic('walk')}My matches</div>`+MINE().map(m=>`<div class="bc run"><h4>You vs <b>${esc(m.vs||'Player')}</b>${m.status==='disputed'?' · Under review':''}</h4><div class="in"><span><small>Entry Fee</small><strong>${coin}${nf(m.stake)}</strong></span><span class="r"><small>Winning Prize</small><strong>${coin}${nf(m.prize)}</strong></span></div>${m.status==='running'?`<button class="btn play2" data-a="play" data-id="${m.id}">Play Ludo now</button>`:''}</div>`).join(''):'';
const VD=['0123456789','1234067895','2340178956','3401289567','4012395678','5987604321','6598710432','7659821043','8765932104','9876543210'],VP=['0123456789','1576283094','5803796142','8916043527','9453126870','4286573901','2793806415','7046913258'];
const aadhaarOk=a=>/^[2-9]\d{11}$/.test(a)&&[...a].reverse().reduce((c,x,i)=>+VD[c][+VP[i%8][+x]],0)===0;
const wdList=()=>(S.wds||[]).length?`<div class="bar">${ic('bank')}Recent withdrawals</div><div class="card">`+S.wds.map(w=>`<div class="tx"><span>${fmt(w.amount)} <small>${esc((w.method||'').toUpperCase())} · ${new Date(w.at).toLocaleDateString()}</small></span><span class="tg ${w.status==='paid'?'closed':''}">${esc(w.status)}</span></div>`).join('')+'</div>':'';
const tkList=()=>(S.tickets||[]).length?`<div class="bar">${ic('chat')}My tickets</div>`+S.tickets.map(t=>`<div class="card"><b>${esc(t.subject)}</b> <span class="tg ${t.status}">${t.status}</span><br><small>${new Date(t.created_at).toLocaleDateString()}</small>${t.reply?`<p class="rp"><b>Support:</b> ${esc(t.reply)}</p>`:''}</div>`).join(''):'';
const SEL={cpu:2,pass:2},LOC={get:()=>{try{return JSON.parse(localStorage.fb_local||'null')}catch{return null}},set:v=>localStorage.fb_local=JSON.stringify(v),clear:()=>localStorage.removeItem('fb_local')};
const segs=g=>`<div class="seg">${[2,3,4].map(n=>`<button class="${n===2?'on':''}" data-a="seg" data-g="${g}" data-v="${n}">${n} Players</button>`).join('')}</div>`;
const battleBody=()=>{const o=S.battles.filter(b=>b.st==='open'),r=S.battles.filter(b=>b.st==='running').slice(0,30);
  return`${mm()}<div class="note">${esc(CFG.NOTICE)}</div><div class="card"><div class="hd"><b>Create a Battle</b><a class="rl" data-a="rules">Rules <i>${ic('info')}</i></a></div><div class="row"><input id="coin" type="number" inputmode="numeric" min="${CFG.MIN_STAKE}" placeholder="Entry coins (min 50)"><button class="btn dark sm" data-a="set">Create</button></div><div class="err" id="e"></div></div>
  <div class="bar">${ic('walk')}Open Battles</div>${o.length?o.map(bCard).join(''):'<p class="empty">No open battles. Create one above.</p>'}<div class="bar">${ic('walk')}Running Battles</div>${r.length?r.map(bCard).join(''):'<p class="empty">No battles running.</p>'}`};
const AMTS=[100,250,500,1000,1500,2000,2500,5000];
const V={
 ludo:()=>`<div class="lhx"><div class="lhx-t"><span class="lhx-b">PREMIUM</span><h2>Ludo Classic</h2><p>Online battle · real players · real prizes</p></div>${art(0)}</div>
 ${battleBody()}
 <div class="card lm"><h3>How to play</h3><ul class="rl2"><li>Roll a 6 to bring a token out of your yard.</li><li>A 6, a capture or reaching home gives you another roll.</li><li>Land on an opponent to send their token back (not on safe squares: stars and start squares).</li><li>Three 6s in a row lose your turn. Exact roll needed to reach home.</li></ul></div>`,
 game:()=>`<div class="gm"><div class="gtop"><button class="gb" data-a="gexit" aria-label="Back">${ic('arr')}</button><b>Ludo Classic</b><button class="gb" data-a="snd" aria-label="Sound">${ic(localStorage.fb_snd==='0'?'mute':'snd')}</button><span class="gpz">${coin}<span id="gpz"></span></span></div><div class="pl" id="pl"></div><div class="bw">${boardSVG()}</div><div class="dz"><div id="dz"></div><p id="gs"></p><p id="gl"></p></div></div>`,
 admin:()=>{if(REAL)return'<p class="empty">Admins: open /admin.html</p>';const p=S.user.kycs==='pending'&&S.kycForm;return`<h2>Demo admin</h2><p class="sub" style="margin-bottom:10px">Manual KYC review (demo only). Real admins use /admin.html.</p>${p?`<div class="card"><b>${esc(p.name)}</b><br><small>${esc(p.email)} · ${esc(p.mobile)} · DOB ${esc(p.dob)}<br>Aadhaar …${esc(p.last4)}<br>${esc(p.address)}</small><div class="row" style="margin-top:12px"><button class="btn ok sm" data-a="dapprove">Approve</button><button class="btn out sm" data-a="dreject">Reject</button></div></div>`:'<p class="empty">No KYC waiting for review.</p>'}`},
 home:()=>`<div class="wel"><b>Welcome to Night Elite Ludo</b><span>${S.ann?'':'Pick a game and start playing'}</span>${S.ann?`<p class="wel-a">${esc(S.ann)}</p>`:''}</div><div class="hd"><h2>All Games</h2><button class="rules" data-a="rules">Rules ${ic('arr')}</button></div>
<button class="hg" data-a="game" aria-label="Play Ludo Classic"><img class="hg-img" src="assets/ludo-classic.jpg" alt="Ludo Classic" width="1200" height="487" decoding="async"><span class="hg-p">PLAY NOW ${ic('arr')}</span></button>
<div class="sc2"><button class="sc soon" data-a="soon" aria-label="Ludo Snake, coming soon"><img class="sc-img sn" src="assets/ludo-snake.jpg" alt="Ludo Snake" width="1200" height="740" loading="lazy" decoding="async"></button><button class="sc sup" data-a="gosup" aria-label="Support"><img class="sc-img su" src="assets/support.jpg" alt="Support. Need help?" width="1200" height="690" loading="lazy" decoding="async"></button></div>`,
 battle:()=>battleBody(),
 addmoney:()=>`<div class="amh"><button class="gb" data-a="amback" aria-label="Back">${ic('arr')}</button><b>Add Money</b></div><div class="card am"><small>Enter amount</small><div class="amin"><span>₹</span><input id="amt" type="number" inputmode="numeric" min="10" max="10000" placeholder="0" autocomplete="off"></div><small>Min ₹10 · Max ₹10,000</small><div class="amg">${AMTS.map(v=>`<button data-a="q" data-v="${v}">₹${v}</button>`).join('')}</div><button class="btn amnext" data-a="amnext">NEXT</button><div class="err" id="e"></div></div>`,
 pay:()=>`<div class="pay" id="pay"><p class="empty">Loading payment…</p></div>`,
 wallet:()=>`<div class="wc"><span class="wi r1">${ic('wallet')}</span><div><b>Deposit Coin</b><h3>${fmt(S.user.funds)}</h3></div><button class="btn teal" data-a="add">Add Cash ${ic('plus')}</button><p>Use to play Ludo Classic. Cannot be withdrawn.</p></div>
  <div class="wc"><span class="wi r2">${ic('wallet')}</span><div><b>Winning Coin</b><h3>${fmt(S.user.income)}</h3></div><button class="btn out" data-a="wd">Withdraw ${ic('bank')}</button><p>Withdraw to your UPI or bank account. Also usable for play.</p></div>${wdList()}`,
 refer:()=>`<div class="card pad0"><div class="hero"><b>PLAY. WIN.<br>REPEAT.</b><span>GET 2% LIFETIME<br>REFERRAL COMMISSION</span></div><div class="share"><p>Share your referral code and earn <b>2%</b> lifetime commission</p><div class="row"><div class="refcode">${ic('gift')}${S.user.ref}</div><button class="btn ok sm" data-a="copy">${ic('copy')} Copy</button></div><small>SHARE VIA</small><div class="row"><a class="btn ok" target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent('Play on Night Elite Ludo! Use my code '+S.user.ref)}"><span class="ci">${ic('wa')}</span>WhatsApp</a><a class="btn tgb" target="_blank" rel="noopener" href="https://t.me/share/url?url=${encodeURIComponent(location.origin)}&text=${encodeURIComponent('Use my code '+S.user.ref)}"><span class="ci">${ic('tg')}</span>Telegram</a></div></div></div>
  <div class="card"><h3 class="lt">Lifetime Earnings</h3><div class="row"><div class="sm2"><span class="wi p">${ic('user')}</span><div><small>Referral Players</small><b>${S.user.refs}</b></div></div><div class="sm2"><span class="wi g">${ic('wallet')}</span><div><small>Referral Earning</small><b>₹${nf(S.user.refEarn||0)}</b></div></div></div></div>`,
 profile:()=>{const u=S.user;return`<div class="pf"><span class="av">${avatar}</span><div><h3>${esc(u.name)}</h3><small>${esc(u.phone)}</small></div><button class="pen" data-a="edit" aria-label="Edit name">${ic('pen')}</button></div>
  <div class="kpi"><div><b>${nf(u.won)}</b><span>Total won</span><i class="k1">₹</i></div><div><b>${u.games}</b><span>Games played</span><i class="k2">${ic('star')}</i></div></div>
  <div class="kyc"><div><b>KYC Status</b>${u.kyc?'Verified <em>'+ic('check')+'</em>':u.kycs==='pending'?'Pending admin review':u.kycs==='rejected'?'Rejected — '+esc(u.kycNote||'please resubmit'):'Not completed'}</div>${u.kyc?'':u.kycs==='pending'?(REAL?'':'<a class="btn sm yl" href="#/admin">Demo admin</a>'):'<button class="btn sm yl" data-a="kyc">Complete KYC</button>'}</div>
  <div class="list">${li('history','clock','History')}${li('wallet','wallet','My Wallet')}${li('refer','gift','Refer &amp; Earn')}${li('support','chat','Support')}<button class="li lo" data-a="out"><span>${ic('out')}</span>Logout<em>${ic('arr').replace('M5 12h14M13 6l6 6-6 6','M9 6l6 6-6 6')}</em></button></div>`},
 history:()=>{const p=+(sessionStorage.hp||1),l=S.ledger.slice(0,p*10);return`<h2>History</h2><div class="card">${l.length?l.map(x=>`<div class="tx"><span>${esc(x.t)}<br><small class="sub">${new Date(x.at).toLocaleString()}</small></span><b class="${x.a>0?'p':'m'}">${x.a>0?'+':''}${x.a}</b></div>`).join(''):'<p class="empty">No transactions yet. Add cash or join a battle.</p>'}</div>${S.ledger.length>l.length?'<button class="btn out" data-a="more">Load more</button>':''}`},
 notifications:()=>{S.notes.forEach(n=>n.r=1);save();REAL&&API.markRead();return`<h2>Notifications</h2>${S.notes.length?S.notes.slice(0,30).map(n=>`<div class="card">${esc(n.m)}<br><small class="sub">${new Date(n.at).toLocaleString()}</small></div>`).join(''):'<p class="empty">Nothing new. Battle results appear here.</p>'}`},
 support:()=>{const c=(i,t,s,cl,h)=>`<${h?'a target="_blank" rel="noopener" href="'+h+'"':'div'} class="ch ${h?'':'off'}"><span class="wi ${cl}">${ic(i)}</span><div><b>${t}</b><small>${s}</small></div>${h?'<em>›</em>':''}</${h?'a':'div'}>`;
  return`<h2 class="big">Support</h2><p class="sub" style="margin:-8px 0 14px">Choose a channel to get help</p><button class="ch" data-a="newtk"><span class="wi r1">${ic('chat')}</span><div><b>Chat Support</b><small>Send us a message</small></div><em>›</em></button>${c('wa','WhatsApp Support','Message us on WhatsApp','g',CFG.WA)}${c('tg','Telegram Support','Currently unavailable','b')}${tkList()}`}
};
let TM;
function login(step='phone',err=''){clearInterval(TM);LAST='';const left=()=>S.otp?Math.max(0,CFG.OTP_COOLDOWN-Math.floor((Date.now()-S.otp.at)/1e3)):0;
 $('#app').innerHTML=`<div class="login">${new URLSearchParams(location.search).get('ref')?`<span class="tag">${ic('uplus')} Referral invite active</span>`:''}<div class="lgw"><img class="lgs" src="assets/logo.png" alt="Night Elite Ludo" width="280" height="280"></div><div class="lc"><h3>Login</h3><div class="lb">
${step==='phone'?`<div class="ph"><span>+91</span><input id="ph" type="tel" inputmode="numeric" maxlength="10" placeholder="Mobile Number" autocomplete="tel"></div><p class="terms">By continuing, you agree to our Terms and confirm that you are 18 or older.</p><button class="btn" data-a="go">Send OTP</button>`
:`<input id="ot" class="otp" inputmode="numeric" maxlength="6" placeholder="Enter OTP" autocomplete="one-time-code"><button class="btn" data-a="vf">Verify OTP</button><div class="two"><span id="rs"></span><a data-a="chg">Change number</a></div>${!REAL?'<p class="terms">Demo mode: any 6-digit code works.</p>':''}`}
<div class="err" id="e">${esc(err)}</div></div></div></div>${wa}`;
 const rs=$('#rs');if(rs){const t=()=>{rs.innerHTML=left()?'Resend in '+left()+'s':'<a data-a="resend">Resend OTP</a>'};t();TM=setInterval(t,1e3)}
 const f=$('#ph')||$('#ot');f&&f.focus()}
function render(){if(!S.user||S.otp)return login(S.otp?'otp':'phone');
 const[r,AV]=(location.hash.slice(2)||'home').split('/'),k=V[r]?r:'home',nk=k==='battle'||k==='game'||k==='ludo'?'home':k==='pay'||k==='addmoney'?'wallet':k,m=$('#app>main');ARG=AV;
 if(!m)$('#app').innerHTML=head()+`<main>${V[k]()}</main>`+nav(nk)+wa+drawer;
 else{$('#app>header').outerHTML=head();m.innerHTML=V[k]();$('#app>nav').outerHTML=nav(nk)}
 if(k!==LAST){const mm=$('#app>main');mm.classList.remove('pg');void mm.offsetWidth;mm.classList.add('pg');if(LAST)scrollTo(0,0);LAST=k}
 document.body.classList.toggle('ingame',k==='game');document.body.classList.toggle('inpay',k==='pay'||k==='addmoney');if(k==='game')startGame(ARG);else stopGame();if(k==='pay')startPay(ARG);else stopPay();
 if(k==='home'&&'Notification'in window&&Notification.permission==='default'&&!sessionStorage.pa){sessionStorage.pa=1;perm()}}
let LAST='',DP,ARG='',G={};
const modal=(h,c='')=>{let m=$('#modal');if(!m){m=document.createElement('div');m.id='modal';document.body.append(m)}m.innerHTML=`<div class="mb" data-a="mc"></div><div class="md ${c}">${h}</div>`;m.className='on'};
const mc=()=>{const m=$('#modal');m&&(m.className='')};
const perm=()=>modal(`<div class="mh"><span class="wi r1">${ic('shield')}</span><h3>Permissions</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><p class="sub">Allow notifications to get battle results and alerts. Tap Allow on the browser prompt.</p><div class="pr"><span class="wi r1">${ic('bell')}</span><div><b>Notifications</b><small>Battle results and account alerts</small></div></div><div class="row" style="margin-top:14px"><button class="btn" data-a="allow">Allow</button><button class="btn gr" data-a="mc">Later</button></div>`);
async function act(f,ok){try{await f();ok&&toast(ok);render()}catch(x){toast(x.message);const e=$('#e');e&&(e.textContent=x.message)}}
const lo=()=>{REAL&&sb.auth.signOut();S.user=null;S.otp=null;save();location.hash='';render()};
const A={seg:t=>{document.querySelectorAll('[data-g="'+t.dataset.g+'"]').forEach(b=>b.classList.toggle('on',b===t));SEL[t.dataset.g]=+t.dataset.v},
 startcpu:()=>newLocal('cpu',SEL.cpu),startpass:()=>newLocal('pass',SEL.pass),resume:()=>location.hash='#/game/free',again:()=>{const l=G.loc;mc();stopGame();newLocal(l.mode,l.n)},
 amback:()=>history.length>1?history.back():location.hash='#/wallet',
 amnext:async t=>{const v=Math.round(+$('#amt').value*100)/100,e=$('#e');if(!(v>=10&&v<=10000)){e&&(e.textContent='Enter an amount between ₹10 and ₹10,000.');return}t.disabled=true;e&&(e.textContent='');try{const x=await API.createQr(v);location.hash='#/pay/'+x.order_id}catch(x){e&&(e.textContent=x.message);t.disabled=false}},
 qrnew:async t=>{const d=PY.data;if(!d)return;t.disabled=true;try{const x=await API.createQr(d.amount);location.replace('#/pay/'+x.order_id)}catch(x){toast(x.message);t.disabled=false}},
 qrdl:()=>qrDownload(),
 paydone:()=>{location.hash='#/wallet'},payretry:()=>{location.hash='#/addmoney'},
 snd:()=>{localStorage.fb_snd=SND()?'0':'1';const b=$('[data-a="snd"]');b&&(b.innerHTML=ic(SND()?'snd':'mute'))},play:t=>location.hash='#/game/'+t.dataset.id,gosup:()=>location.hash='#/support',soon:()=>toast('Ludo Snake is coming soon'),gexit:()=>{mc();location.hash='#/ludo'},
 roll:()=>{const st=G.state;if(!st||st.winner!=null||st.seats[st.turn]!==G.me||st.phase!=='roll'||G.busy||Date.now()<(G.animEnd||0))return;G.demo?apply(window.Ludo.roll(st,1+Math.floor(Math.random()*6))):gameAct('roll')},
 tok:t=>{const st=G.state,i=+t.dataset.i;if(!st||+t.dataset.q!==G.me||st.seats[st.turn]!==G.me||st.phase!=='move'||G.busy||Date.now()<(G.animEnd||0)||!window.Ludo.legal(st).includes(i))return;G.demo?apply(window.Ludo.move(st,i)):gameAct('move',i)},
 claimto:()=>gameAct('claim'),dapprove:()=>{S.user.kycs='verified';S.user.kyc=true;S.kycForm=null;S.notes.unshift({m:'Your KYC is verified',at:Date.now(),r:0});save();toast('KYC approved');location.hash='#/profile';render()},
 dreject:()=>{const x=prompt('Reason shown to the user','Photo is blurry. Please upload clear photos.');if(!x)return;S.user.kycs='rejected';S.user.kycNote=x;S.kycForm=null;S.notes.unshift({m:'Your KYC was rejected: '+x,at:Date.now(),r:0});save();toast('KYC rejected');location.hash='#/profile';render()},newtk:()=>modal(`<div class="mh"><h3>Chat Support</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><input id="ts" maxlength="120" placeholder="Subject"><textarea id="tb" maxlength="2000" rows="4" placeholder="Describe your problem"></textarea><button class="btn" style="margin-top:12px" data-a="sendtk">Send message</button><div class="err" id="e"></div>`),sendtk:()=>act(async()=>{await API.ticket($('#ts').value.trim(),$('#tb').value.trim());mc()},'Message sent'),room:t=>act(()=>API.setRoom(t.dataset.id,$('#rc-'+t.dataset.id).value.trim()),'Room code saved'),claim:t=>act(()=>API.report(t.dataset.id,t.dataset.v),'Result reported'),
 menu:()=>$('#drawer').classList.add('open'),dclose:(t,e)=>{if(t.id==='drawer'&&e.target!==t)return;$('#drawer').classList.remove('open')},
 mc:(t,e)=>{mc()},out:lo,game:()=>location.hash='#/ludo',
 rules:()=>modal(`<div class="mh"><h3>Rules</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><ol class="rl2"><li>Entry fee is locked when you create or join a battle.</li><li>Winner gets the prize after a ${CFG.FEE*200}% platform fee.</li><li>Open battles can be cancelled for a full refund.</li><li>Demo mode uses sandbox coins only.</li></ol>`),
 join:t=>act(()=>API.join(t.dataset.id),'Battle joined'),cancel:t=>act(()=>API.cancel(t.dataset.id),'Battle cancelled, stake refunded'),
 set:()=>act(()=>API.create(+$('#coin').value),'Battle created'),
 add:()=>REAL&&FBC.PAYMENTS?(location.hash='#/addmoney'):modal(`<div class="mh"><h3>Add Cash</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><input id="amt" type="number" inputmode="numeric" placeholder="Amount (₹10 – ₹10,000)"><div class="row" style="margin:10px 0">${[100,500,1000].map(v=>`<button class="btn out sm" data-a="q" data-v="${v}">₹${v}</button>`).join('')}</div><button class="btn ok" data-a="addgo">${REAL&&FBC.PAYMENTS?'Pay &amp; add cash':'Add cash (demo)'}</button><div class="err" id="e"></div>`),
 q:t=>{$('#amt').value=t.dataset.v},addgo:()=>{const v=+$('#amt').value;if(REAL&&FBC.PAYMENTS)return act(()=>API.pay(v));act(async()=>{await API.addCash(v);mc()},'Cash added (demo)')},
 wd:()=>{if(!S.user.kyc){toast(S.user.kycs==='pending'?'Your KYC is under review.':'Complete KYC to withdraw.');if(S.user.kycs!=='pending')A.kyc();return}modal(`<div class="mh"><h3>Withdraw</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><input id="wa" type="number" inputmode="numeric" value="${Math.floor(S.user.income)}" placeholder="Amount (min ₹100)"><select id="wm" class="sel" aria-label="Payout method"><option value="upi">UPI</option><option value="bank">Bank transfer</option></select><input id="wd" placeholder="UPI ID (name@bank) or account no. + IFSC"><button class="btn" style="margin-top:12px" data-a="wdgo">Request withdrawal</button><div class="err" id="e"></div>`)},
 wdgo:()=>act(async()=>{await API.withdraw(+$('#wa').value,$('#wm').value,$('#wd').value.trim());mc()},'Withdrawal requested'),
 kyc:()=>{KB={};modal(`<div class="kh"><span class="idb">ID</span><div><h3>Upload Aadhaar</h3><p>Manual check, usually same day</p></div><button data-a="mc" aria-label="Close">${ic('x')}</button></div>
<div class="fld"><label for="kn">Aadhaar Name *</label><input id="kn" maxlength="80" placeholder="Aadhaar Name *" autocomplete="name"></div>
<div class="fld"><label for="ka">Aadhaar Number *</label><input id="ka" inputmode="numeric" maxlength="14" placeholder="Aadhaar Number *" autocomplete="off"><div class="kv" id="kv"></div></div>
<div class="fld"><label for="kd">Date of Birth *</label><input id="kd" type="date" max="${new Date(Date.now()-18*31557600000).toISOString().slice(0,10)}"></div>
<div class="fld"><label for="ke">Email *</label><input id="ke" type="email" maxlength="120" placeholder="Email *" autocomplete="email"></div>
<div class="fld"><label for="kad">Address *</label><input id="kad" maxlength="200" placeholder="Address *" autocomplete="street-address"></div>
<div class="tiles"><label class="up tile"><input type="file" id="kf" accept="image/png,image/jpeg" hidden><img alt=""><i class="cr c1"></i><i class="cr c2"></i><i class="cr c3"></i><i class="cr c4"></i><div class="ti"><span class="ico">${ic('scan')}</span><b>Front side</b><small>Aadhaar photo page</small><span class="fmt">${ic('cam')} PNG / JPG</span></div></label><label class="up tile"><input type="file" id="kb" accept="image/png,image/jpeg" hidden><img alt=""><i class="cr c1"></i><i class="cr c2"></i><i class="cr c3"></i><i class="cr c4"></i><div class="ti"><span class="ico">${ic('scan')}</span><b>Back side</b><small>Address side</small><span class="fmt">${ic('cam')} PNG / JPG</span></div></label></div>
<div class="kn">${ic('scan')}<span>Enter your name exactly as on Aadhaar. Blurry photos may be rejected. Photos are compressed on your phone before upload.</span></div>
<label class="ck"><input type="checkbox" id="kc"><span>I agree to verification of these details. Photos are used only for review; only the last 4 digits of the Aadhaar number are kept.</span></label><button class="btn" data-a="kycgo">Submit for review</button><div class="err" id="e"></div>`,'kycm')},
 kycgo:()=>act(async()=>{if(!$('#kc').checked)throw Error('Please accept the consent to continue.');await API.kyc($('#kn').value,$('#ke').value.trim(),S.user.phone,$('#kd').value,$('#ka').value.replace(/\D/g,''),$('#kad').value.trim());KB={};mc()},'KYC submitted'),more:()=>{sessionStorage.hp=+(sessionStorage.hp||1)+1;render()},
 copy:()=>navigator.clipboard?.writeText(S.user.ref).then(()=>toast('Code copied'),()=>toast('Copy failed')),
 edit:()=>modal(`<div class="mh"><h3>Edit name</h3><button data-a="mc" aria-label="Close">${ic('x')}</button></div><input id="nm" maxlength="20" value="${esc(S.user.name)}"><button class="btn" style="margin-top:12px" data-a="savenm">Save</button>`),
 savenm:async()=>{const v=$('#nm').value.trim();if(v.length<3)return toast('Name needs 3+ characters');if(REAL){const{error}=await sb.from('profiles').update({name:v}).eq('id',UID);if(error)return toast('Could not save name')}S.user.name=v;save();mc();render()},
 allow:()=>{mc();Notification.requestPermission()},
 install:async(t,e)=>{e.preventDefault();$('#drawer').classList.remove('open');if(DP){DP.prompt();DP=null}else toast('Browser menu → Add to Home screen')},
 go:()=>run(async()=>{await API.sendOtp($('#ph').value.trim());login('otp')}),
 vf:()=>run(async()=>{await API.verifyOtp($('#ot').value.trim());location.hash='#/home';render()}),
 chg:()=>{S.otp=null;login()},resend:()=>run(async()=>{await API.sendOtp(S.otp.p);login('otp')})
};
const run=async f=>{try{await f()}catch(x){const e=$('#e');e?e.textContent=x.message:toast(x.message)}};
document.addEventListener('click',e=>{const t=e.target.closest('[data-a]');if(!t)return;const a=A[t.dataset.a];if(a){if(t.tagName==='A'&&t.dataset.a!=='dclose')e.preventDefault();a(t,e)}});
document.addEventListener('input',e=>{if(e.target.id==='ph'||e.target.id==='ot')e.target.value=e.target.value.replace(/\D/g,'')});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.closest('.login'))$('.login .btn').click();if(e.key==='Escape')mc()});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();DP=e});
document.addEventListener('input',e=>{if(e.target.id==='ka'){const d=e.target.value.replace(/\D/g,'').slice(0,12),v=$('#kv'),ok=aadhaarOk(d);e.target.value=d.replace(/(\d{4})(?=\d)/g,'$1 ');v.textContent=d.length<12?'':ok?'Aadhaar number looks valid ✓':'This Aadhaar number is not valid';v.className='kv '+(d.length<12?'':ok?'ok':'bad')}});
/* ---- Ludo game screen ---- */
const COL=['#e53935','#2e9d4f','#f6b800','#1e6fe0'],PIPS={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const die=d=>'<div class="die">'+[...Array(9)].map((_,i)=>`<i class="${(PIPS[d]||[]).includes(i)?'on':''}"></i>`).join('')+'</div>';
const boardSVG=()=>{const cell=(r,c,f,st)=>`<rect x="${c}" y="${r}" width="1" height="1" fill="${f}" stroke="${st||'#d6cdf5'}" stroke-width=".05"/>`;
 const G4=[['#ff9a94','#d32f2f'],['#7de39a','#1b8a3e'],['#ffe27a','#e0a100'],['#7dbaff','#1558c9']];
 let o='<svg viewBox="0 0 15 15" class="bd" role="img" aria-label="Ludo board"><defs>'+G4.map(([a,b],k)=>`<radialGradient id="g${k}" cx=".35" cy=".3" r=".8"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></radialGradient><linearGradient id="y${k}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient>`).join('')+'<linearGradient id="gold" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#EDE8FF"/><stop offset=".5" stop-color="#6D4AFF"/><stop offset="1" stop-color="#EDE8FF"/></linearGradient><radialGradient id="bgp" cx=".5" cy=".5" r=".75"><stop offset="0" stop-color="#ffffff"/><stop offset="1" stop-color="#ece7ff"/></radialGradient></defs><rect width="15" height="15" fill="url(#bgp)"/>';
 [[0,0],[0,9],[9,9],[9,0]].forEach(([r,c],k)=>{o+=`<rect x="${c}" y="${r}" width="6" height="6" fill="url(#y${k})"/><rect x="${c+.8}" y="${r+.8}" width="4.4" height="4.4" rx=".7" fill="#ffffff" stroke="${COL[k]}" stroke-opacity=".4" stroke-width=".06"/>`;[[2,2],[2,4],[4,2],[4,4]].forEach(([a,b])=>o+=`<circle cx="${c+b}" cy="${r+a}" r=".66" fill="${COL[k]}" opacity=".14"/><circle cx="${c+b}" cy="${r+a}" r=".52" fill="none" stroke="${COL[k]}" stroke-width=".07" opacity=".6"/>`)});
 const L=window.Ludo;if(!L)return o+'</svg>';
 L.TRACK.forEach(([r,c],i)=>{const k=L.START.indexOf(i);o+=cell(r,c,k>=0?`url(#y${k})`:'#ffffff');if(k>=0)o+=`<text x="${c+.5}" y="${r+.74}" text-anchor="middle" font-size=".7" fill="#fff" opacity=".9">★</text>`;else if([8,21,34,47].includes(i))o+=`<text x="${c+.5}" y="${r+.76}" text-anchor="middle" font-size=".8" fill="#8a6bff">★</text>`});
 for(let q=0;q<4;q++)for(let p=51;p<=55;p++){const[r,c]=L.cellRC(q,p);o+=cell(r,c,`url(#y${q})`,'#ffffff80')}
 o+=`<polygon points="6,6 6,9 7.5,7.5" fill="url(#y0)"/><polygon points="6,6 9,6 7.5,7.5" fill="url(#y1)"/><polygon points="9,6 9,9 7.5,7.5" fill="url(#y2)"/><polygon points="6,9 9,9 7.5,7.5" fill="url(#y3)"/><rect x="6" y="6" width="3" height="3" fill="none" stroke="#ffffffaa" stroke-width=".05"/><circle cx="7.5" cy="7.5" r=".55" fill="url(#gold)" stroke="#fff" stroke-width=".06"/><circle cx="7.5" cy="7.5" r=".22" fill="#fff" opacity=".85"/><rect x=".05" y=".05" width="14.9" height="14.9" fill="none" stroke="url(#gold)" stroke-width=".1"/>`;
 return o+'<g id="tk"></g></svg>'};
const myTurn=()=>{const st=G.state;return st&&st.winner==null&&st.seats[st.turn]===G.me};
function drawAll(){const st=G.state,L=window.Ludo,tk=$('#tk');if(!st||!tk||!L)return;
 if(!tk.children.length)tk.innerHTML=st.seats.map(q=>[0,1,2,3].map(i=>`<g class="tk" id="t${q}${i}" data-a="tok" data-q="${q}" data-i="${i}" style="transform:translate(7.5px,7.5px)"><ellipse cy=".26" rx=".38" ry=".14" fill="#0005"/><circle r=".4" fill="url(#g${q})" stroke="#fff" stroke-width=".09"/><circle r=".22" fill="none" stroke="#fff" stroke-width=".05" opacity=".6"/><circle r=".1" fill="#fff" opacity=".9"/><circle cx="-.14" cy="-.15" r=".11" fill="#fff" opacity=".6"/></g>`).join('')).join('');
 const sh=G.shown||st.tok,grp={};st.seats.forEach(q=>(sh[q]||st.tok[q]).forEach((p,i)=>{const[x,y]=L.xy(q,p,i),k=x+','+y;(grp[k]=grp[k]||[]).push([q,i,x,y])}));
 const idle=Date.now()>=(G.animEnd||0)-20,mv=myTurn()&&st.phase==='move'&&idle?L.legal(st):[];
 Object.values(grp).forEach(g=>g.forEach(([q,i,x,y],j)=>{const o=g.length>1?[[-.2,-.2],[.2,-.2],[-.2,.2],[.2,.2]][j%4]:[0,0],e=$(`#t${q}${i}`);if(!e)return;e.style.transform=`translate(${x+o[0]}px,${y+o[1]}px)`;e.classList.toggle('mv',q===G.me&&mv.includes(i))}));
 const rem=!G.free&&!G.demo&&st.deadline&&st.winner==null?Math.max(0,Math.ceil((st.deadline-Date.now())/1000)):null,cur=st.seats[st.turn];
 if(G.free){const g=$('.gpz');g&&(g.textContent='Free play')}else{const z=$('#gpz');z&&(z.textContent=nf(G.info.prize))}
 $('#pl').innerHTML=(G.free?st.seats:[G.me,...st.seats.filter(q=>q!==G.me)]).map(q=>`<div class="pc ${cur===q&&st.winner==null?'act':''}"><i style="background:${COL[q]}">${esc(gname(q)[0]).toUpperCase()}</i><div><b>${esc(gname(q))}</b><small>Home ${st.tok[q].filter(p=>p===56).length}/4${cur===q&&rem!=null?' · '+rem+'s':''}</small></div></div>`).join('');
 const rolling=G.rollAt&&Date.now()-G.rollAt<450,ready=myTurn()&&st.phase==='roll'&&idle;
 $('#dz').innerHTML=`<button class="dice ${ready?'ready':''} ${rolling?'rolling':''}" data-a="roll" aria-label="Roll dice">${die(rolling?1+Math.floor(Math.random()*6):st.dice)}</button>`;
 const who=G.mode==='pass'?esc(gname(cur))+' — ':'';
 $('#gs').innerHTML=st.winner!=null?esc(gname(st.winner))+' won!':myTurn()?who+(st.phase==='roll'?(G.mode==='pass'?'tap the dice':'Your turn — tap the dice'):(G.mode==='pass'?'tap a glowing token':'Tap a glowing token')):(rem===0?'<button class="btn sm" data-a="claimto">Opponent timed out — claim win</button>':esc(gname(cur))+' is playing…');
 const l=st.last,gl=$('#gl');if(gl)gl.textContent=l?`${gname(l.seat)} rolled ${l.roll}${l.cap?' · captured a token!':''}${l.to===56?' · reached home!':''}${l.roll===6&&!l.cap&&l.to!==56&&st.winner==null?' · rolls again':''}`:''}
const gname=q=>G.names?G.names[q]:(q===G.me?'You':(G.info&&G.info.vs)||'Opponent');
function syncShown(st){const sh=G.shown=G.shown||{};G.seq=G.seq||{};let end=0;const jumps=[];
 st.seats.forEach(q=>{const cur=sh[q]=sh[q]||[...st.tok[q]];st.tok[q].forEach((p,i)=>{const from=cur[i];if(from===p)return;const key=q+':'+i,id=G.seq[key]=(G.seq[key]||0)+1;
  if(from>=0&&p>from){const n=p-from;end=Math.max(end,n*150);for(let k=1;k<=n;k++)setTimeout(()=>{if(G.seq[key]!==id)return;cur[i]=from+k;drawAll()},k*150)}else jumps.push([cur,i,p,key,id])})});
 G.animEnd=Date.now()+end;jumps.forEach(([cur,i,p,key,id])=>setTimeout(()=>{if(G.seq[key]!==id)return;cur[i]=p;drawAll()},end+(end?60:0)));if(end)setTimeout(drawAll,end+80)}
let AC=null;const SND=()=>localStorage.fb_snd!=='0';
function tone(f,d,ty='sine',v=.07,t=0){if(!SND())return;try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();if(AC.state==='suspended')AC.resume();const o=AC.createOscillator(),g=AC.createGain(),t0=AC.currentTime+t;o.type=ty;o.frequency.setValueAtTime(f,t0);g.gain.setValueAtTime(v,t0);g.gain.exponentialRampToValueAtTime(.0001,t0+d);o.connect(g);g.connect(AC.destination);o.start(t0);o.stop(t0+d)}catch{}}
function sfx(st){const l=st.last;if(!l)return;for(let i=0;i<5;i++)tone(260+Math.random()*220,.05,'square',.035,i*.07);
 if(l.tok!==undefined){for(let k=0;k<Math.min(l.roll,6);k++)tone(520,.07,'triangle',.07,.4+k*.15);if(l.cap){tone(300,.3,'sawtooth',.07,.4+l.roll*.15);navigator.vibrate&&navigator.vibrate(120)}if(l.to===56)[523,659,784].forEach((f,i)=>tone(f,.16,'sine',.08,.5+l.roll*.15+i*.12))}}
const sfxWin=()=>[523,659,784,1047].forEach((f,i)=>tone(f,.22,'sine',.09,i*.13));
function botPlay(){const L=window.Ludo,s=G.state;if(!s||s.winner!=null)return;apply(s.phase==='roll'?L.roll(s,1+Math.floor(Math.random()*6)):L.move(s,L.botPick(s)))}
function apply(st){const old=G.state;G.state=st;if(G.mode==='pass'&&st.winner==null)G.me=st.seats[st.turn];
 if(st.last&&JSON.stringify(st.last)!==JSON.stringify(old&&old.last)){G.rollAt=Date.now();setTimeout(drawAll,470);if(old)sfx(st)}
 syncShown(st);drawAll();
 if(G.free)LOC.set({...G.loc,state:st});else if(G.demo){S.games=S.games||{};S.games[G.id]=st;save()}
 const wait=Math.max(0,(G.animEnd||0)-Date.now());
 if(st.winner!=null&&!G.done){G.done=1;const w=st.winner;if(G.free)LOC.clear();else G.demo?API.demoFinish(G.id,w===G.me):API.refresh();
  const ttl=G.free?(G.mode==='pass'?gname(w)+' won! 🎉':w===0?'You won! 🎉':'Computer won'):(w===G.me?'You won! 🎉':'You lost');
  setTimeout(()=>{sfxWin();modal(`<div class="mh"><h3>${esc(ttl)}</h3></div><p class="sub">${G.free?'Good game!':w===G.me?'Prize added to your winnings.':'Better luck next time.'}</p><div class="row" style="margin-top:14px">${G.free?'<button class="btn ok" data-a="again">Play again</button>':''}<button class="btn ${G.free?'out':''}" data-a="gexit">${G.free?'Exit':'Back to battles'}</button></div>`)},1100+wait)}
 else if(G.demo){clearTimeout(G.bt);const q=st.seats[st.turn];if(st.winner==null&&(G.free?G.bots.includes(q):q!==G.me))G.bt=setTimeout(botPlay,950+wait)}}
function newLocal(mode,n){const L=window.Ludo;if(!L)return toast('Loading… try again in a moment');const seats=n===2?[0,2]:n===3?[0,1,2]:[0,1,2,3];LOC.set({mode,n,state:L.newGame(seats.map(q=>'p'+q),seats)});location.hash='#/game/free'}
async function startFree(){const loc=LOC.get();if(!loc){toast('No game in progress.');location.hash='#/ludo';return}
 await new Promise(ok=>{const w=()=>window.Ludo?ok():setTimeout(w,30);w()});if(location.hash!=='#/game/free')return;
 const cn=['Red','Green','Yellow','Blue'];G={id:'free',free:1,demo:1,loc,mode:loc.mode,info:{prize:0},names:{},me:0,bots:loc.mode==='cpu'?loc.state.seats.filter(q=>q!==0):[]};
 loc.state.seats.forEach((q,k)=>G.names[q]=loc.mode==='cpu'?(q===0?'You':'Computer'+(loc.n===2?'':' '+k)):cn[q]);
 const o=$('.bw');o&&(o.innerHTML=boardSVG());apply(loc.state);G.tick=setInterval(drawAll,1000)}
async function gameAct(action,token){G.busy=1;try{const{data:{session}}=await sb.auth.getSession();const r=await fetch('/api/game/act',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({battle_id:G.id,action,token})}).then(x=>x.json());if(r.state)apply(r.state);else if(r.error!=='RETRY')toast(r.error==='NOT_YET'?'Wait a moment before claiming.':'Move not allowed.');else await gameSync()}catch{toast('Network error. Try again.')}G.busy=0}
async function gameSync(){try{const{data}=await sb.from('games').select('state').eq('battle_id',G.id).maybeSingle();if(data&&JSON.stringify(data.state)!==JSON.stringify(G.state))apply(data.state)}catch{}}
async function startGame(id){if(G.id===id&&G.state){drawAll();return}stopGame();if(id==='free'){location.hash='#/ludo';return}const info=MINE().find(m=>m.id===id);if(!info||info.status!=='running'){G={};toast('This match is not available.');location.hash='#/ludo';return}
 await new Promise(ok=>{const w=()=>window.Ludo?ok():setTimeout(w,30);w()});if(location.hash!=='#/game/'+id)return;
 const L=window.Ludo;G={id,info,demo:!REAL};
 if(!REAL){const bt=S.battles.find(b=>b.id===id);G.me=0;const st=(S.games||{})[id]||L.newGame(['me','bot']);const o=$('.bw');o&&(o.innerHTML=boardSVG()+'');apply(st)}
 else{const{data:{session}}=await sb.auth.getSession(),r=await fetch('/api/game/act',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({battle_id:id,action:'sync'})}).then(x=>x.json()).catch(()=>({}));
  if(!r.state){toast('Could not open the game.');location.hash='#/ludo';return}G.me=L.seatOf(r.state,UID);const o=$('.bw');o&&(o.innerHTML=boardSVG());apply(r.state);
  G.ch=sb.channel('g'+id).on('postgres_changes',{event:'*',schema:'public',table:'games',filter:'battle_id=eq.'+id},p=>p.new&&p.new.state&&apply(p.new.state)).subscribe();G.poll=setInterval(gameSync,4000)}
 G.tick=setInterval(drawAll,1000)}
function stopGame(){if(!G.id&&!G.tick)return;clearTimeout(G.bt);clearInterval(G.tick);clearInterval(G.poll);if(G.ch&&sb)sb.removeChannel(G.ch);G={}}
/* ---- QR payment screen: UI only. Success is shown ONLY after the server (webhook-verified DB status) says so. ---- */
let PY={};
const mmss=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
async function payLoad(){if(!PY.id)return;const id=PY.id,x=await API.apiF('/api/payments/status?order_id='+encodeURIComponent(id));if(PY.id!==id)return;
 if(x.error){PY.err=x.error;paintPay();return}
 const was=PY.data&&PY.data.status;PY.data={...(PY.data||{}),...x};PY.exp=Date.now()+(new Date(x.expires_at)-x.now);if(x.qr)PY.data.qrKeep=x.qr;
 if(x.status!=='pending'){clearInterval(PY.poll);clearInterval(PY.tick);if(x.status==='success'&&was!=='success')API.refresh().then(()=>{const h=$('#app>header');h&&(h.outerHTML=head())})}paintPay()}
function startPay(id){if(PY.id===id&&PY.data){paintPay();return}stopPay();if(!REAL||!/^fb_[a-f0-9]{32}$/.test(id||'')){location.hash='#/wallet';return}PY={id};payLoad();PY.poll=setInterval(payLoad,3000);PY.tick=setInterval(paintPay,1000)}
function stopPay(){clearInterval(PY.poll);clearInterval(PY.tick);PY={}}
function paintPay(){const el=$('#pay');if(!el)return;const d=PY.data;
 const top=`<div class="amh"><button class="gb" data-a="${d&&d.status==='pending'?'amback':'paydone'}" aria-label="Back">${ic('arr')}</button><b>Pay</b><span class="secure">${ic('shield')} Secure</span></div>`;
 if(!d){el.innerHTML=top+(PY.err?`<p class="empty">${esc(PY.err==='NOT_FOUND'?'Payment not found.':'Could not load this payment.')}</p><button class="btn" data-a="payretry">Add Money</button>`:'<p class="empty">Loading payment…</p>');return}
 const amt=fmt(d.amount);let secs=Math.max(0,Math.ceil((PY.exp-Date.now())/1000)),st=d.status;
 if(st==='pending'&&secs<=0){st='expired';d.status='expired';clearInterval(PY.poll);payLoad()}
 if(st==='pending'){const cur=el.querySelector('.qrt');if(cur&&el.dataset.s==='pending'){cur.textContent=mmss(secs);return}
  el.dataset.s='pending';el.innerHTML=top+`<div class="pcard"><div class="brand">${logo}</div><h3>Scan QR to Pay</h3><small>Amount to pay</small><div class="pamt">${amt}</div><div class="qrbox"><img id="qr" src="${d.qr||d.qrKeep||''}" alt="Payment QR for ${esc(amt)}"></div><div class="qrx">QR expires in <b class="qrt ${secs<60?'low':''}">${mmss(secs)}</b></div><div class="pref">Order: ${esc(d.reference||'')}</div><button class="btn" data-a="qrdl">Download QR</button><div class="wait"><i></i><i></i><i></i> Waiting for payment…</div><p class="pnote">Open any UPI app, scan this QR and pay. This page updates automatically.</p></div>`;return}
 el.dataset.s=st;
 const box=st==='success'?`<div class="pst ok"><span>${ic('check')}</span><h3>Payment Successful</h3><p>${amt} payment received</p><button class="btn ok" data-a="paydone">Back to wallet</button></div>`
  :st==='failed'?`<div class="pst bad"><span>${ic('x')}</span><h3>Payment Failed</h3><p>Please try again</p><button class="btn" data-a="payretry">Try again</button></div>`
  :`<div class="pst ex"><span>${ic('clock')}</span><h3>QR Expired</h3><p>This QR is no longer valid.</p><button class="btn" data-a="qrnew">Generate New QR</button></div>`;
 el.innerHTML=top+`<div class="pcard">${box}<div class="pref">Order: ${esc(d.reference||'')}</div></div>`}
async function qrDownload(){const d=PY.data,src=d&&(d.qr||d.qrKeep);if(!d||d.status!=='pending'||!src)return toast('QR not available');
 const save=(blob)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='NightEliteLudo-PAY-'+String(d.reference||'').replace(/^[A-Za-z]+-/,'')+'.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);toast('QR downloaded')};
 try{const img=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src}),c=document.createElement('canvas');c.width=640;c.height=860;const g=c.getContext('2d');
  g.fillStyle='#fff';g.fillRect(0,0,640,860);g.fillStyle='#2b2a33';g.textAlign='center';g.font='700 40px sans-serif';g.fillText('Night Elite Ludo',320,70);g.font='500 26px sans-serif';g.fillStyle='#6f6b78';g.fillText('Amount to pay',320,125);g.font='800 64px sans-serif';g.fillStyle='#2b2a33';g.fillText(fmt(d.amount),320,200);
  g.drawImage(img,70,230,500,500);g.font='500 24px sans-serif';g.fillStyle='#6f6b78';g.fillText('Order: '+d.reference,320,785);g.font='500 20px sans-serif';g.fillText('Scan with any UPI app',320,825);
  const b=await new Promise(r=>c.toBlob(r,'image/png'));if(!b)throw 0;save(b)}
 catch{try{const b=await fetch(src).then(r=>r.blob());save(b)}catch{window.open(src,'_blank');toast('Long-press the QR to save it')}}}
let KB={};
const shrink=(f,max=1280)=>new Promise((ok,no)=>{if(!/^image\//.test(f.type))return no(Error('Choose an image file.'));const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);const k=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=Math.round(i.width*k);c.height=Math.round(i.height*k);c.getContext('2d').drawImage(i,0,0,c.width,c.height);const go=q=>c.toBlob(b=>!b?no(Error('Could not process the image.')):b.size>450e3&&q>.4?go(q-.12):ok(b),'image/jpeg',q);go(.72)};i.onerror=()=>{URL.revokeObjectURL(u);no(Error('Could not read this image. Use a JPG or PNG photo.'))};i.src=u});
document.addEventListener('change',async e=>{const t=e.target;if(t.id!=='kf'&&t.id!=='kb')return;const k=t.id==='kf'?'f':'b',l=t.closest('.up'),sp=l.querySelector('span'),f=t.files[0];if(!f)return;sp.textContent='Compressing…';
 try{const b=await shrink(f);KB[k]=b;l.querySelector('img').src=URL.createObjectURL(b);l.classList.add('has');sp.textContent=(k==='f'?'Front':'Back')+' photo ready · '+Math.round(b.size/1024)+' KB (was '+Math.round(f.size/1024)+' KB)'}
 catch(x){KB[k]=null;l.classList.remove('has');sp.textContent=x.message}});
document.addEventListener('click',()=>{try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();AC.resume()}catch{}},{once:true});
addEventListener('hashchange',render);
const soft=()=>{if(/^#\/(game|pay)/.test(location.hash)){const h=$('#app>header');h&&(h.outerHTML=head());return}const f=document.activeElement;if(f&&f.tagName==='INPUT'){const v=f.value,id=f.id;render();const n=id&&$('#'+id);n&&(n.value=v,n.focus())}else render()};
setInterval(()=>{if(S.user&&API.settle())soft()},2000);
setInterval(async()=>{if(REAL&&S.user&&!document.hidden&&await API.refresh())soft()},6000);
document.addEventListener('visibilitychange',()=>{if(REAL&&S.user&&!document.hidden)API.refresh().then(c=>c&&soft())});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('/sw.js');
if(new URLSearchParams(location.search).get('order_id')){history.replaceState({},'','/');location.hash='#/wallet';setTimeout(()=>toast('Payment received? Balance updates in a moment.'),800)}
REAL?API.boot().then(render):render();
