const agentForm=(v={})=>UI.form([{k:'name',label:'Name'},{k:'mobile',label:'Mobile'},{k:'email',label:'Email',type:'email'},{k:'role',label:'Type',type:'select',opts:['Agent','Sub Admin','Admin']},{k:'status',label:'Status',type:'select',opts:['Active','Inactive']}],v);
Pages.data('agents',{res:'agents',title:'Agents',mod:'agents',sub:'Agents are separate from customer referral users.',
 top:el=>{el.innerHTML='<div class="grid g4" style="margin-bottom:12px">'+['Total Agents','Active Agents','Customers Acquired','Current Month Acquisitions'].map(l=>UI.stat(l,'—')).join('')+'</div>'},
 create:{label:'+ Create',open:()=>{const f=agentForm();UI.modal({title:'Create Agent / Admin',body:f,actions:[{label:'Cancel'},{label:'Create',cls:'p',run:()=>Api.action('agent.create',f.values())}]})}},
 filters:[{k:'status',l:'Status',o:['Active','Inactive']}],
 cols:[{k:'id',l:'Agent ID'},{k:'name',l:'Name'},{k:'mobile',l:'Mobile'},{k:'email',l:'Email'},{k:'status',l:'Status',b:1},{k:'customers',l:'Customers'},{k:'created',l:'Created'}],
 actions:r=>[{label:'Edit',perm:'edit',run:()=>{const f=agentForm(r);UI.modal({title:'Edit '+r.id,body:f,actions:[{label:'Cancel'},{label:'Save',cls:'p',run:()=>Api.action('agent.update',{id:r.id,...f.values()})}]})}},
  r.status==='Active'?{label:'Deactivate',perm:'edit',danger:1,confirm:'Deactivate '+r.name+'?',run:()=>Api.action('agent.deactivate',{id:r.id})}:{label:'Activate',perm:'edit',confirm:'Activate '+r.name+'?',run:()=>Api.action('agent.activate',{id:r.id})}],
 detail:r=>{const n=document.createElement('div');n.innerHTML=UI.kv({'Agent ID':r.id,Name:r.name,Mobile:r.mobile,Email:r.email,Status:UI.html(UI.badge(r.status)),Created:r.created})+'<h4>Acquired customers</h4><p class="hint">'+r.customers+' customers (list loads from server)</p><h4>Acquisition statistics</h4><p class="hint">Charts load from server aggregates.</p><h4>Activity / Audit log</h4><p class="hint">Server-side audit entries for this agent.</p>';UI.modal({title:'Agent '+r.id,drawer:true,body:n,actions:[{label:'Close'}]})}});
