/* Reuses the existing customer-facing announcements system (read by customer Home). Writes go through a backend action. */
const annForm=v=>{const f=UI.form([{k:'title',label:'Title'},{k:'message',label:'Message',type:'textarea',max:500,hint:'Plain text. Shown on customer Home under Welcome.'},{k:'status',label:'Status',type:'select',opts:['Draft','Active','Expired']},{k:'priority',label:'Priority',type:'select',opts:['Normal','High','Low']},{k:'start',label:'Start date',type:'date'},{k:'expiry',label:'Expiry date',type:'date'}],v);
 const p=document.createElement('div');p.className='card';p.style.marginTop='12px';const draw=()=>{const x=f.values();p.innerHTML='<small class="hint">PREVIEW (customer Home)</small><div class="msg" style="margin:6px 0 0"><b>Welcome to Night Elite Ludo</b><div style="white-space:pre-line;overflow-wrap:anywhere;max-height:5.4em;overflow:auto">'+UI.esc(x.message||'Your message appears here')+'</div></div>'};f.oninput=draw;draw();const w=document.createElement('div');w.append(f,p);w.values=f.values;return w};
const save=(w,id)=>async()=>{const v=w.values();if(!v.message.trim()){UI.toast('Message is required.','er');return false}await Api.action('announcement.save',{id,...v})};
Pages.data('announcements',{res:'announcements',title:'Announcements',mod:'announcements',sub:'Shown on the customer Home page next to the Welcome message.',tabs:[{k:'all',label:'All'},{k:'active',label:'Active'},{k:'draft',label:'Draft'},{k:'expired',label:'Expired'}],
 create:{label:'+ New announcement',open:()=>{const w=annForm({});UI.modal({title:'New announcement',body:w,actions:[{label:'Cancel'},{label:'Save',cls:'p',run:save(w)}]})}},
 cols:[{k:'title',l:'Title'},{k:'message',l:'Message',r:r=>`<span style="display:inline-block;max-width:260px;overflow:hidden;text-overflow:ellipsis;vertical-align:bottom">${UI.esc(r.message)}</span>`},{k:'status',l:'Status',b:1},{k:'start',l:'Start'},{k:'expiry',l:'Expiry'},{k:'priority',l:'Priority'}],
 actions:r=>[{label:'Edit',perm:'edit',run:()=>{const w=annForm(r);UI.modal({title:'Edit announcement',body:w,actions:[{label:'Cancel'},{label:'Save',cls:'p',run:save(w,r.id)}]})}},
  r.status==='Active'?{label:'Deactivate',perm:'edit',confirm:'Deactivate this announcement?',run:()=>Api.action('announcement.deactivate',{id:r.id})}:{label:'Activate',perm:'edit',confirm:'Activate this announcement?',run:()=>Api.action('announcement.activate',{id:r.id})},
  {label:'Delete',perm:'delete',danger:1,confirm:'Delete this announcement permanently?',run:()=>Api.action('announcement.delete',{id:r.id})}],
 detail:r=>UI.modal({title:r.title,drawer:true,body:UI.kv(r)})});
