/* Reusable UI components: icon, badge, toast, modal/drawer, confirm, tabs, form, states */
(function(){
const ICONS={dash:'<rect x="3" y="3" width="7" height="9"/><rect x="14" y="3" width="7" height="5"/><rect x="14" y="12" width="7" height="9"/><rect x="3" y="16" width="7" height="5"/>',users:'<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20c0-3.5 3-6 6.5-6s6.5 2.5 6.5 6M16 4.5a3.5 3.5 0 0 1 0 7M18 14c2.2.6 3.5 2.6 3.5 6"/>',kyc:'<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="9" cy="11" r="2.5"/><path d="M5.5 16c.5-1.5 1.8-2.2 3.5-2.2s3 .7 3.5 2.2M15 10h4M15 14h3"/>',wallet:'<path d="M3 7a2 2 0 0 1 2-2h13v4"/><rect x="3" y="7" width="18" height="13" rx="2"/><circle cx="16.5" cy="13.5" r="1.2"/>',card:'<rect x="2.5" y="5" width="19" height="14" rx="2"/><path d="M2.5 10h19M6 15h4"/>',out:'<path d="M12 20V6M6 11l6-6 6 6M5 20h14"/>',dice:'<rect x="4" y="4" width="16" height="16" rx="3"/><circle cx="9" cy="9" r="1"/><circle cx="15" cy="15" r="1"/><circle cx="12" cy="12" r="1"/>',trophy:'<path d="M8 4h8v5a4 4 0 0 1-8 0zM8 6H4v1a3 3 0 0 0 4 3M16 6h4v1a3 3 0 0 1-4 3M12 13v4M8 20h8"/>',gift:'<rect x="3" y="9" width="18" height="11" rx="1"/><path d="M12 9v11M3 13h18M12 9c-2-4-6-3-5 0M12 9c2-4 6-3 5 0"/>',agent:'<circle cx="12" cy="8" r="3.5"/><path d="M5 20c0-4 3-6 7-6s7 2 7 6M17 3l2 2-2 2"/>',shield:'<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/><path d="M9 12l2 2 4-4"/>',mega:'<path d="M4 10v4h3l8 4V6L7 10zM18 9a4 4 0 0 1 0 6"/>',bell:'<path d="M6 16V11a6 6 0 0 1 12 0v5l2 2H4zM10 21h4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.7.4-1 .9-1 1.7M12 17h.01"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',tune:'<path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',log:'<path d="M6 3h9l4 4v14H6z"/><path d="M9 12h7M9 16h7M9 8h3"/>',out2:'<path d="M9 4H5v16h4M16 8l4 4-4 4M20 12H9"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',x:'<path d="M6 6l12 12M18 6L6 18"/>',dot:'<circle cx="12" cy="12" r="3"/>'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const G='approved active success completed resolved verified unlocked finished credit deposit refund enabled sent live',A='pending processing waiting draft open "in progress" full scheduled unread not submitted'.split(' '),R='rejected failed locked cancelled expired inactive debit frozen disabled error';
function badge(s){const k=String(s).toLowerCase();const c=G.split(' ').includes(k)?'g':A.includes(k)?'a':R.split(' ').includes(k)?'r':['admin','super admin','sub admin','agent'].includes(k)?'v':'';return `<span class="bd ${c}">${esc(s)}</span>`}
const icon=n=>`<svg class="ic" viewBox="0 0 24 24" aria-hidden="true">${ICONS[n]||ICONS.dot}</svg>`;
function toast(m,t='info'){const h=document.getElementById('toast'),d=document.createElement('div');d.className=t;d.textContent=m;h.appendChild(d);setTimeout(()=>d.remove(),4200)}
function modal({title,body,actions=[],drawer=false,onClose}){const o=document.createElement('div');o.className='ov'+(drawer?' dr':'');o.innerHTML=`<div class="mo" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="mh"><h3>${esc(title)}</h3><button class="ib" aria-label="Close" data-x>${icon('x')}</button></div><div class="mb"></div>${actions.length?'<div class="mf"></div>':''}</div>`;
 const b=o.querySelector('.mb');typeof body==='string'?b.innerHTML=body:b.appendChild(body);
 const close=()=>{o.remove();document.removeEventListener('keydown',kd);onClose&&onClose()},kd=e=>e.key==='Escape'&&close();document.addEventListener('keydown',kd);
 o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-x]'))close()});
 const f=o.querySelector('.mf');actions.forEach(a=>{const x=document.createElement('button');x.className='btn '+(a.cls||'');x.textContent=a.label;x.onclick=async()=>{x.disabled=true;try{const r=await a.run?.(o);if(r!==false&&!a.keep)close()}catch(e){toast(e.message||'Action failed','er')}x.disabled=false};f.appendChild(x)});
 document.body.appendChild(o);(o.querySelector('input,select,textarea,.btn')||o.querySelector('.ib')).focus();return{close,el:o}}
const confirmDlg=({title,msg,danger,label='Confirm'})=>new Promise(res=>{let done=false;const m=modal({title,body:`<p>${esc(msg)}</p>`,onClose:()=>done||res(false),actions:[{label:'Cancel',keep:false},{label,cls:danger?'d':'p',run:()=>{done=true;res(true)}}]})});
function tabs(items,active,on){const w=document.createElement('div');w.className='tabs';w.setAttribute('role','tablist');items.forEach(t=>{const b=document.createElement('button');b.textContent=t.label;b.setAttribute('role','tab');if(t.k===active)b.className='on';b.onclick=()=>{w.querySelectorAll('button').forEach(x=>x.className='');b.className='on';on(t.k)};w.appendChild(b)});return w}
const skeleton=(n=6)=>Array.from({length:n},(_,i)=>`<div class="sk" style="width:${95-i*6}%"></div>`).join('');
const empty=(m='Nothing to show yet.')=>`<div class="es"><div style="font-size:28px">🗂️</div><p>${esc(m)}</p></div>`;
const errorBox=(m,retry)=>{const d=document.createElement('div');d.className='es er';d.innerHTML=`<div style="font-size:28px">⚠️</div><p>${esc(m)}</p>`;if(retry){const b=document.createElement('button');b.className='btn';b.textContent='Retry';b.onclick=retry;d.appendChild(b)}return d};
const kv=o=>`<dl class="kv">${Object.entries(o).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${v==null||v===''?'—':(v&&v.__h)?v.__h:esc(v)}</dd>`).join('')}</dl>`;
const html=h=>({__h:h});
/* form: fields [{k,label,type,opts,hint,value}] -> returns element with .values() */
function form(fields,vals={}){const f=document.createElement('form');f.className='fm';f.onsubmit=e=>e.preventDefault();f.innerHTML=fields.map(x=>{const v=vals[x.k]??x.value??'';const inp=x.type==='select'?`<select name="${x.k}">${x.opts.map(o=>`<option ${o==v?'selected':''}>${esc(o)}</option>`).join('')}</select>`:x.type==='textarea'?`<textarea name="${x.k}" maxlength="${x.max||2000}">${esc(v)}</textarea>`:`<input name="${x.k}" type="${x.type||'text'}" value="${esc(v)}">`;return `<label>${esc(x.label)}${inp}${x.hint?`<span class="hint">${esc(x.hint)}</span>`:''}</label>`}).join('');f.values=()=>Object.fromEntries(new FormData(f));return f}
const stat=(l,v)=>`<div class="card stat"><small>${esc(l)}</small><b>${esc(v)}</b></div>`;
window.UI={esc,icon,badge,toast,modal,confirm:confirmDlg,tabs,skeleton,empty,errorBox,kv,html,form,stat};
})();
