const adminForm=v=>UI.form([{k:'name',label:'Name'},{k:'email',label:'Email',type:'email'},{k:'mobile',label:'Mobile'},{k:'role',label:'Role',type:'select',opts:['Super Admin','Admin','Sub Admin']},{k:'status',label:'Status',type:'select',opts:['Active','Inactive']}],v);
const matrix=()=>`<div class="mx"><div class="tw"><table><thead><tr><th>Module</th>${ACTIONS.map(a=>`<th>${a[0].toUpperCase()+a.slice(1)}</th>`).join('')}</tr></thead><tbody>${MODULES.map(m=>`<tr><td>${m[0].toUpperCase()+m.slice(1)}</td>${ACTIONS.map(a=>`<td><input type="checkbox" aria-label="${m} ${a}" data-m="${m}" data-a="${a}"></td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;
Pages.data('admins',{res:'admins',title:'Admins & Permissions',mod:'admins',sub:'Access is role-based. Permissions are enforced by the backend, never by this UI.',
 create:{label:'+ Create Admin',open:()=>{const f=adminForm({});UI.modal({title:'Create Admin',body:f,actions:[{label:'Cancel'},{label:'Create',cls:'p',run:()=>Api.action('admin.create',f.values())}]})}},
 top:el=>{el.innerHTML='<div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;align-items:center"><b>Role permission matrix</b><select id="rl" aria-label="Role"><option>Super Admin</option><option>Admin</option><option>Sub Admin</option></select></div><p class="hint">Each role has View / Create / Edit / Approve / Reject / Delete per module. Defaults are loaded from the server role definitions.</p>'+matrix()+'<div style="margin-top:10px"><button class="btn p" id="sv">Save permissions</button></div></div>';
  const set=()=>{const r=el.querySelector('#rl').value;el.querySelectorAll('input[type=checkbox]').forEach(c=>{c.checked=false;c.disabled=!Permissions.can('admins','edit')})};set();el.querySelector('#rl').onchange=set;
  el.querySelector('#sv').onclick=async()=>{if(await UI.confirm({title:'Save permissions',msg:'Update permissions for '+el.querySelector('#rl').value+'?',danger:1}))try{await Api.action('role.permissions',{role:el.querySelector('#rl').value,matrix:[...el.querySelectorAll('input:checked')].map(c=>c.dataset.m+':'+c.dataset.a)})}catch(e){UI.toast(e.message,'er')}}},
 cols:[{k:'name',l:'Name'},{k:'email',l:'Email'},{k:'mobile',l:'Mobile'},{k:'role',l:'Role',b:1},{k:'status',l:'Status',b:1},{k:'last',l:'Last Login'},{k:'created',l:'Created'}],
 actions:r=>[{label:'Edit',perm:'edit',run:()=>{const f=adminForm(r);UI.modal({title:'Edit admin',body:f,actions:[{label:'Cancel'},{label:'Save',cls:'p',run:()=>Api.action('admin.update',f.values())}]})}},{label:'Deactivate',perm:'delete',danger:1,confirm:'Deactivate '+r.name+'?',run:()=>Api.action('admin.deactivate',{email:r.email})}],
 detail:r=>UI.modal({title:r.name,drawer:true,body:UI.kv(r)})});
